=== OrcaBus/service-workflow-manager/docs/events/WorkflowRunUpdate/WorkflowRunUpdate.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/OrcaBus/service-workflow-manager/refs/heads/main/docs/events/WorkflowRunUpdate/WorkflowRunUpdate.schema.json",
  "description": "EventBridge custom event schema for WorkflowRunUpdate events",
  "title": "AWSEvent",
  "definitions": {
    "WorkflowRunUpdate": {
      "type": "object",
      "required": [
        "portalRunId",
        "workflowRunName",
        "workflow",
        "libraries",
        "status"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "orcabusId": {
          "type": "string"
        },
        "portalRunId": {
          "type": "string"
        },
        "executionId": {
          "type": "string"
        },
        "workflowRunName": {
          "type": "string"
        },
        "workflow": {
          "$ref": "#/definitions/Workflow"
        },
        "analysisRun": {
          "$ref": "#/definitions/AnalysisRun"
        },
        "libraries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Library"
          }
        },
        "computeEnv": {
          "type": "string"
        },
        "storageEnv": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "payload": {
          "$ref": "#/definitions/Payload"
        }
      }
    },
    "Library": {
      "type": "object",
      "required": [
        "libraryId",
        "orcabusId"
      ],
      "properties": {
        "libraryId": {
          "type": "string"
        },
        "orcabusId": {
          "type": "string"
        },
        "readsets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Readset"
          }
        }
      }
    },
    "Readset": {
      "type": "object",
      "required": [
        "orcabusId",
        "rgid"
      ],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "rgid": {
          "type": "string"
        }
      }
    },
    "Workflow": {
      "type": "object",
      "required": [
        "orcabusId"
      ],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "codeVersion": {
          "type": "string"
        },
        "executionEngine": {
          "type": "string"
        },
        "executionEnginePipelineId": {
          "type": "string"
        },
        "validationState": {
          "type": "string"
        }
      }
    },
    "AnalysisRun": {
      "type": "object",
      "required": [
        "orcabusId",
        "name"
      ],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Payload": {
      "type": "object",
      "required": [
        "version",
        "data"
      ],
      "properties": {
        "refId": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "data": {
          "type": "object"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "time": {
      "format": "date-time",
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/WorkflowRunUpdate"
    }
  },
  "required": [
    "detail",
    "detail-type",
    "source"
  ]
}

=== OrcaBus/service-workflow-manager/docs/events/WorkflowRunUpdate/examples/WRU__example1.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunUpdate",
  "source": "anything except orcabus.workflowmanager e.g. orcabus.manual or orcabus.manual.alexis or orcabus.ui.joep, ...",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "portalRunId": "202405012397gatc",
    "workflowRunName": "<name assinged to the workflow run> e.g. manual--research-workflow-xx2-123",
    "workflow": {
      "orcabusId": "wfl.01J5M2JFE1JPYV62RYQEG99CPW",
      "name": "<the name of the workflow when registered with workflow manager> e.g. bssh_icav2_fastq_copy",
      "version": "<the version of the workflow when registered with workflow manager> e.g. 1.2.3",
      "executionEngine": "<the execution platform of the workflow when registered with workflow manager> e.g. ICAv2"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G7074NKTGN"
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEG99CP5"
      }
    ],
    "status": "DRAFT"
  }
}

=== OrcaBus/service-workflow-manager/app/workflow_manager_proc/tests/fixtures/WRU_min.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunUpdate",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "portalRunId": "202405012397gatc",
    "workflowRunName": "540424_A01001_0193_BBBBMMDRX5 FASTQ Copy",
    "workflow": {
      "orcabusId": "wfl.01J5M2JFE1JPYV62RYQEG99CPW"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G7074NKTGN"
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEG99CP5"
      }
    ],
    "status": "DRAFT"
  }
}

=== OrcaBus/service-workflow-manager/app/workflow_manager_proc/tests/fixtures/WRU_draft_1.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunUpdate",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "portalRunId": "202405012397gatc",
    "workflowRunName": "TestWorkflowRunNo1",
    "workflow": {
      "orcabusId": "wfl.01J5M2JFE1JPYV62RYQEG99CPW"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G7074NKTGN"
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEG99CP5"
      }
    ],
    "status": "DRAFT",
    "payload": {
      "version": "0.1.0",
      "data": {
        "projectId": "axxxxxxxx-axxx-1xxxx-aaaa-xxxxxxxxx",
        "executionId": "12345678-238c-4200-b632-d5dd8c8db94a",
        "outputUriPrefix": "icav2://12345678-32d3-4c76-a324-c6a85dae87b5/ilmn_primary/"
      }
    }
  }
}

=== OrcaBus/service-workflow-manager/app/workflow_manager_proc/tests/fixtures/WRSC_max.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunStateChange",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "97534601940f17ebcfee02enotsecret",
    "version": "1.0.0",
    "timestamp": "2025-05-01T09:25:44Z",
    "orcabusId": "wfr.01J5M2J44HFJ9424G7074HHHHH",
    "portalRunId": "202405012397gatc",
    "workflowRunName": "540424_A01001_0193_BBBBMMDRX5 FASTQ Copy",
    "workflow": {
      "orcabusId": "wfl.01J5M2JFE1JPYV62RYQEG99CPW",
      "name": "bssh_icav2_fastq_copy",
      "version": "1.2.3",
      "executionEngine": "ICA"
    },
    "analysisRun": {
      "orcabusId": "anr.01J5M2JFE1JPYV62RYQEG99RUN",
      "name": "wgts-dna"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G7074NKTGN"
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEG99CP5"
      }
    ],
    "status": "READY",
    "payload": {
      "orcabusId": "pld.01J5M2J44HFJ9424G7074PPPPP",
      "refId": "99995678-238c-4200-b632-d5dd8c8db94a",
      "version": "0.1.0",
      "data": {
        "projectId": "bxxxxxxxx-dxxx-4xxxx-adcc-xxxxxxxxx",
        "executionId": "12345678-238c-4200-b632-d5dd8c8db94a",
        "outputUriPrefix": "icav2://12345678-32d3-4c76-a324-c6a85dae87b5/ilmn_primary/"
      }
    }
  }
}

=== OrcaBus/service-workflow-manager/docs/events/WorkflowRunStateChange/examples/WRSC__example1.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunStateChange",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "<hash(values)> e.g. 97534601940f17ebcfee02e9df998244",
    "version": "<semver> e.g. 1.0.0",
    "timestamp": "2025-05-01T09:25:44Z",
    "orcabusId": "wfr.<ULID> e.g. wfr.01J5M2J44HFJ9424G7074HHHHH",
    "portalRunId": "202405012397gatc",
    "workflowRunName": "<fill-by-workflow-manager> e.g. 540424_A01001_0193_BBBBMMDRX5 FASTQ Copy",
    "workflow": {
      "orcabusId": "wfl.01J5M2JFE1JPYV62RYQEG99CPW",
      "name": "<fill-by-workflow-manager> e.g. bssh_icav2_fastq_copy",
      "version": "<fill-by-workflow-manager> e.g. 1.2.3",
      "executionEngine": "<fill-by-workflow-manager> e.g. ICAv2"
    },
    "analysisRun": {
      "orcabusId": "anr.01J5M2JFE1JPYV62RYQEG99RUN",
      "name": "wgts-dna"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G7074NKTGN"
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEG99CP5"
      }
    ],
    "status": "READY",
    "payload": {
      "orcabusId": "pld.<ULID> e.g. pld.01J5M2J44HFJ9424G7074PPPPP",
      "refId": "<fill-by-workflow-manager> e.g. <uuid>",
      "version": "0.1.0",
      "data": {
        "projectId": "bxxxxxxxx-dxxx-4xxxx-adcc-xxxxxxxxx",
        "executionId": "12345678-238c-4200-b632-d5dd8c8db94a",
        "outputUriPrefix": "icav2://12345678-32d3-4c76-a324-c6a85dae87b5/ilmn_primary/"
      }
    }
  }
}

=== OrcaBus/service-workflow-manager/docs/events/WorkflowRunUpdate/examples/WRU__example2.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunUpdate",
  "source": "anything except orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "timestamp": "2024-05-01T09:20:00Z",
    "orcabusId": "wfr.<ULID> e.g. wfr.01J5M2J44HFJ9424G7074HHHHH",
    "portalRunId": "202405012397gatc",
    "workflowRunName": "e.g. 540424_A01001_0193_BBBBMMDRX5 FASTQ Copy",
    "workflow": {
      "orcabusId": "wfl.01J5M2JFE1JPYV62RYQEG99CPW",
      "name": "<fill-by-workflow-manager> e.g. bssh_icav2_fastq_copy",
      "version": "<fill-by-workflow-manager> e.g. 1.2.3",
      "codeVersion": "<fill-by-workflow-manager> e.g. 0.0.0",
      "executionEngine": "<fill-by-workflow-manager> e.g. ICA",
      "executionEnginePipelineId": "<fill-by-workflow-manager> e.g. 123.456.789",
      "validationState": "UNVALIDATED"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G7074NKTGN"
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEG99CP5"
      }
    ],
    "status": "RUNNING",
    "payload": {
      "refId": "<fill-by-execution-service> e.g. <uuid>",
      "version": "0.1.0",
      "data": {
        "progress": "80%"
      }
    }
  }
}

=== OrcaBus/service-workflow-manager/app/workflow_manager_proc/tests/fixtures/WRU_max.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunUpdate",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "9a4a56898f96a74c28557df54e760275",
    "version": "1.0.0",
    "timestamp": "2025-05-01T09:25:44Z",
    "orcabusId": "wfr.01J5M2J44HFJ9424G7074HHHHH",
    "portalRunId": "202405012397gatc",
    "executionId": "e4a91a1c-3c2a-4e7e-9b3e-1234567890ab",
    "workflowRunName": "540424_A01001_0193_BBBBMMDRX5 FASTQ Copy",
    "workflow": {
      "orcabusId": "wfl.01J5M2JFE1JPYV62RYQEG99CPW",
      "name": "bssh_icav2_fastq_copy",
      "version": "1.2.3",
      "codeVersion": "0.0.0",
      "executionEngine": "ICA",
      "executionEnginePipelineId": "123.456.789",
      "validationState": "UNVALIDATED"
    },
    "analysisRun": {
      "orcabusId": "anr.01J5M2JFE1JPYV62RYQEG99RUN",
      "name": "wgts-dna"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G7074NKTGN",
        "readsets": [
          {
            "orcabusId": "fqr.READSET123456789ABCDEFGHJK",
            "rgid": "AAGCAGTC+ACGCCAAC.1.990101_A00130_0999_BH7TVMDSX7"
          },
          {
            "orcabusId": "fqr.READSET234567891ABCDEFGHJK",
            "rgid": "AAGCAGTC+ACGCCAAC.2.990101_A00130_0999_BH7TVMDSX7"
          }
        ]
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEG99CP5",
        "readsets": [
          {
            "orcabusId": "fqr.READSET345678912ABCDEFGHJK",
            "rgid": "CCGCAGTC+TCGCCAAC.1.990101_A00130_0999_BH7TVMDSX7"
          },
          {
            "orcabusId": "fqr.READSET456789123ABCDEFGHJK",
            "rgid": "CCGCAGTC+TCGCCAAC.2.990101_A00130_0999_BH7TVMDSX7"
          }
        ]
      }
    ],
    "computeEnv": "clinical",
    "storageEnv": "clinical",
    "status": "READY",
    "payload": {
      "refId": "af7401ac30b18164fafd3f7357726469c6401bef78549375c0b56d3a42bab0d1",
      "version": "0.1.0",
      "data": {
        "projectId": "bxxxxxxxx-dxxx-4xxxx-adcc-xxxxxxxxx",
        "executionId": "12345678-238c-4200-b632-d5dd8c8db94a",
        "outputUriPrefix": "icav2://12345678-32d3-4c76-a324-c6a85dae87b5/ilmn_primary/"
      }
    }
  }
}
