=== OrcaBus/service-workflow-manager/docs/events/schema/AnalysisRunInitiated.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/umccr/orcabus/main/docs/schemas/events/workflowmanager/AnalysisRunStateChange.schema.json",
  "description": "EventBridge custom event schema for orcabus.workflowmanager@AnalysisRunStateChange",
  "title": "AWSEvent",
  "type": "object",
  "required": [
    "detail-type",
    "detail",
    "source"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "time": {
      "type": "string",
      "format": "date-time"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/AnalysisRunInitiated"
    }
  },
  "definitions": {
    "AnalysisRunInitiated": {
      "type": "object",
      "required": [
        "timestamp",
        "analysis",
        "analysisRunName",
        "libraries"
      ],
      "properties": {
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "analysisRunName": {
          "type": "string"
        },
        "analysis": {
          "$ref": "#/definitions/Analysis"
        },
        "libraries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Library"
          }
        },
        "readsets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Readset"
          }
        }
      }
    },
    "Library": {
      "type": "object",
      "required": [
        "libraryId",
        "orcabusId"
      ],
      "properties": {
        "libraryId": {
          "type": "string"
        },
        "orcabusId": {
          "type": "string"
        }
      }
    },
    "Readset": {
      "type": "object",
      "required": [
        "orcabusId"
      ],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "rgid": {
          "type": "string"
        },
        "phenotype": {
          "type": "string"
        }
      }
    },
    "Analysis": {
      "type": "object",
      "required": [
        "orcabusId"
      ],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    }
  }
}

=== OrcaBus/service-workflow-manager/docs/events/schema/examples/ARSC__example1.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "AnalysisRunStateChange",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "orcabusId": "anr.76J5N2J83RED7387G9374NGDBB",
    "timestamp": "2025-05-01T09:25:44Z",
    "status": "DRAFT",
    "analysisRunName": "<unique analysis name>",
    "analysis": {
      "orcabusId": "ana.76J5N2J83RED7387G9374NGDBA",
      "name": "<analysis name>, e.g. oncoanalyser-dna",
      "version": "<analysis version>, e.g. 1.0.4"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G7074NKTGN"
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEG99CP5"
      }
    ],
    "readsets": [
      {
        "orcabusId": "<readset id> fqr.76J5N2J83RED7387G9374NGDBE",
		    "rgid??": "",
        "phenotype??": "normal"
      },
      {
        "orcabusId": "<readset id> fqr.76J5N2J83RED7387G9374NGDBF",
        "phenotype??": "tumor"
      }
    ]
  }
}

=== OrcaBus/service-workflow-manager/docs/events/schema/examples/ARF__example1.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "AnalysisRunInitiated",
  "source": "<some glue service>",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "timestamp": "2025-05-01T09:25:44Z",
    "analysisRunName": "<unique analysis run name>",
    "analysisRunId": "anr.76J5N2J83RED7387G9374NGRUN",
    "analysis": {
      "orcabusId": "ana.76J5N2J83RED7387G9374NGDBA",
      "name": "<analysis name>, e.g. oncoanalyser-dna",
      "version": "<analysis version>, e.g. 1.0.4"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G707NORMAL",
        "readsets": [
          {
            "orcabusId": "<readset id> fqr.76J5N2J83RED7387G9374PAIR1",
            "rgid": "<rgid from FastqListRow>"
          }
        ]
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEGTUMOR",
        "readsets": [
          {
            "orcabusId": "<readset id> fqr.76J5N2J83RED7387G9374PAIR1",
            "rgid": "<rgid from FastqListRow>"
          },
          {
            "orcabusId": "<readset id> fqr.76J5N2J83RED7387G9374PAIR2",
            "rgid": "<rgid from FastqListRow for topup>"
          }
        ]
      }
    ],
    "storageEnv": "<storage env code>, e.g. production",
    "computeEnv": "<compute env code>, e.g. production"
  }
}
