=== OrcaBus/service-workflow-manager/docs/events/AnalysisRunStateChange/AnalysisRunStateChange.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/umccr/orcabus/main/docs/schemas/events/workflowmanager/AnalysisRunStateChange.schema.json",
  "description": "EventBridge custom event schema for AnalysisRunStateChange events",
  "title": "AWSEvent",
  "definitions": {
    "AnalysisRunStateChange": {
      "type": "object",
      "required": [
        "version",
        "id",
        "timestamp",
        "orcabusId",
        "analysisRunName",
        "analysis",
        "status"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "orcabusId": {
          "type": "string"
        },
        "analysisRunName": {
          "type": "string"
        },
        "analysis": {
          "$ref": "#/definitions/Analysis"
        },
        "libraries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Library"
          }
        },
        "computeEnv": {
          "type": "string"
        },
        "storageEnv": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Library": {
      "type": "object",
      "required": ["libraryId", "orcabusId"],
      "properties": {
        "libraryId": {
          "type": "string"
        },
        "orcabusId": {
          "type": "string"
        },
        "readsets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Readset"
          }
        }
      }
    },
    "Readset": {
      "type": "object",
      "required": ["orcabusId"],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "rgid": {
          "type": "string"
        }
      }
    },
    "Analysis": {
      "type": "object",
      "required": ["orcabusId"],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "time": {
      "format": "date-time",
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/AnalysisRunStateChange"
    }
  },
  "required": ["detail", "detail-type", "source"]
}

=== OrcaBus/service-workflow-manager/docs/events/AnalysisRunStateChange/examples/ARSC__example1.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "AnalysisRunStateChange",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "hash(values) e.g. 97534601940f17ebcfee02e9df998244",
    "version": "<semver> e.g. 1.0.0",
    "timestamp": "2025-05-01T09:25:44Z",
    "orcabusId": "anr.76J5N2J83RED7387G9374NGDBB",
    "analysisRunName": "<unique analysis name>",
    "status": "DRAFT",
    "analysis": {
      "orcabusId": "ana.76J5N2J83RED7387G9374NGDBA",
      "name": "<analysis name>, e.g. oncoanalyser-dna",
      "version": "<analysis version>, e.g. 1.0.4"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G7074NKTGN",
        "readsets": [
          {
            "orcabusId": "<readset id> fqr.76J5N2J83RED7387G9374NGDBE",
            "rgid": "CAGCAGTC+ACGCCAAC.4.990720_A00130_0266_BH7TVMDSX7",
            "phenotype??": "normal"
          }
        ]
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEG99CP5",
        "readsets": [
          {
            "orcabusId": "<readset id> fqr.76J5N2J83RED7387G9374NGDBF",
            "rgid": "CAGCAGTC+ACGCCTTC.3.990720_A00130_0266_BH7TVMDSX7",
            "phenotype??": "tumor"
          }
        ]
      }
    ],
    "storageEnv": "<storage env code>, e.g. production",
    "computeEnv": "<compute env code>, e.g. production"
  }
}

=== OrcaBus/service-workflow-manager/docs/events/AnalysisRunStateChange/examples/ARSC__example2.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "AnalysisRunStateChange",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "hash(values) e.g. 97534601940f17ebcfee02e9df998244",
    "version": "<semver> e.g. 1.0.0",
    "timestamp": "2025-05-01T09:25:44Z",
    "orcabusId": "anr.76J5N2J83RED7387G9374NGDBB",
    "analysisRunName": "<unique analysis name>",
    "status": "DRAFT",
    "analysis": {
      "orcabusId": "ana.76J5N2J83RED7387G9374NGDBA",
      "name": "<analysis name>, e.g. oncoanalyser-dna",
      "version": "<analysis version>, e.g. 1.0.4"
    }
  }
}
