=== OrcaBus/service-workflow-manager/docs/events/AnalysisRunUpdate/AnalysisRunUpdate.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/OrcaBus/service-workflow-manager/refs/heads/main/docs/events/AnalysisRunUpdate/AnalysisRunUpdate.schema.json",
  "description": "EventBridge custom event schema for AnalysisRunUpdate events",
  "title": "AWSEvent",
  "definitions": {
    "AnalysisRunUpdate": {
      "type": "object",
      "required": ["analysisRunName", "analysis", "libraries", "status"],
      "properties": {
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "orcabusId": {
          "type": "string"
        },
        "analysisRunName": {
          "type": "string"
        },
        "analysis": {
          "$ref": "#/definitions/Analysis"
        },
        "libraries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Library"
          }
        },
        "computeEnv": {
          "type": "string"
        },
        "storageEnv": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Library": {
      "type": "object",
      "required": ["orcabusId", "libraryId"],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "libraryId": {
          "type": "string"
        },
        "readsets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Readset"
          }
        }
      }
    },
    "Readset": {
      "type": "object",
      "required": ["orcabusId", "rgid"],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "rgid": {
          "type": "string"
        }
      }
    },
    "Analysis": {
      "type": "object",
      "required": ["orcabusId", "name", "version"],
      "properties": {
        "orcabusId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "time": {
      "format": "date-time",
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/AnalysisRunUpdate"
    }
  },
  "required": ["detail", "detail-type", "source"]
}

=== OrcaBus/service-workflow-manager/docs/events/AnalysisRunUpdate/examples/ARU__example_DRAFT.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "AnalysisRunInitiated",
  "source": "<some glue service>",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "analysisRunName": "<unique analysis run name>",
    "analysis": {
      "orcabusId": "ana.76J5N2J83RED7387G9374NGDBA",
      "name": "<analysis name>, e.g. oncoanalyser-dna",
      "version": "<analysis version>, e.g. 1.0.4"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G707NORMAL"
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEGTUMOR"
      }
    ],
    "status": "DRAFT"
  }
}

=== OrcaBus/service-workflow-manager/docs/events/AnalysisRunUpdate/examples/ARU__example_READY.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "AnalysisRunInitiated",
  "source": "<some glue service>",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "hash(value) e.g. 97534601940f17ebcfee02e9df998244",
    "version": "<semver> e.g. 1.0.0",
    "timestamp": "2025-05-01T09:25:44Z",
    "orcabusId": "anr.<ULID> e.g. anr.76J5N2J83RED7387G9374NGRUN",
    "analysisRunName": "<unique analysis run name>",
    "analysis": {
      "orcabusId": "ana.76J5N2J83RED7387G9374NGDBA",
      "name": "<analysis name>, e.g. oncoanalyser-dna",
      "version": "<analysis version>, e.g. 1.0.4"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G707NORMAL",
        "readsets": [
          {
            "orcabusId": "<readset id> fqr.76J5N2J83RED7387G9374PAIR1",
            "rgid": "<rgid from FastqListRow>"
          }
        ]
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEGTUMOR",
        "readsets": [
          {
            "orcabusId": "<readset id> fqr.76J5N2J83RED7387G9374PAIR1",
            "rgid": "<rgid from FastqListRow>"
          },
          {
            "orcabusId": "<readset id> fqr.76J5N2J83RED7387G9374PAIR2",
            "rgid": "<rgid from FastqListRow for topup>"
          }
        ]
      }
    ],
    "storageEnv": "<storage env code>, e.g. production",
    "computeEnv": "<compute env code>, e.g. production",
    "status": "READY"
  }
}

=== OrcaBus/service-workflow-manager/app/workflow_manager_proc/tests/fixtures/ARU_draft_min.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "AnalysisRunUpdate",
  "source": "<some glue service>",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "analysisRunName": "TestAnalysisRunName_1",
    "analysis": {
      "orcabusId": "ana.01K3FSK7ZRED7387G9374NGDBA",
      "name": "WGS",
      "version": "1.0"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.123456789ABCDEFGHJKMNPQRST"
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.223456789ABCDEFGHJKMNPQRST"
      }
    ],
    "status": "DRAFT"
  }
}

=== OrcaBus/service-workflow-manager/app/workflow_manager_proc/tests/fixtures/ARU_draft_max.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "AnalysisRunUpdate",
  "source": "<some glue service>",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "analysisRunName": "TestAnalysisRunName_1",
    "analysis": {
      "orcabusId": "ana.01K3FSK7ZRED738GT4KM7A2E6F",
      "name": "WGS",
      "version": "2.0"
    },
    "libraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.123456789ABCDEFGHJKMNPQRST",
        "readsets": [
          {
            "orcabusId": "fqr.READSET123456789ABCDEFGHJK",
            "rgid": "AAGCAGTC+ACGCCAAC.1.990101_A00130_0999_BH7TVMDSX7"
          },
          {
            "orcabusId": "fqr.READSET234567891ABCDEFGHJK",
            "rgid": "AAGCAGTC+ACGCCAAC.2.990101_A00130_0999_BH7TVMDSX7"
          }
        ]
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.223456789ABCDEFGHJKMNPQRST",
        "readsets": [
          {
            "orcabusId": "fqr.READSET345678912ABCDEFGHJK",
            "rgid": "CCGCAGTC+TCGCCAAC.1.990101_A00130_0999_BH7TVMDSX7"
          },
          {
            "orcabusId": "fqr.READSET456789123ABCDEFGHJK",
            "rgid": "CCGCAGTC+TCGCCAAC.2.990101_A00130_0999_BH7TVMDSX7"
          }
        ]
      }
    ],
    "computeEnv": "research",
    "storageEnv": "research",
    "status": "DRAFT"
  }
}
